version: '3.9'

services:
  current-account-api:
    build:
      context: .
      dockerfile: ./BankMore.CurrentAccount/Dockerfile
    container_name: bankmore-current-account-api
    ports:
      - "8125:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Homologation
    depends_on:
      - kafka
  transfer-api:
    build:
      context: .
      dockerfile: ./BankMore.Transfer/Dockerfile
    container_name: bankmore-transfer-api
    ports:
      - "8126:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - kafka

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Configura dois listeners:
      # - host.docker.internal:9092 → acesso pelo host
      # - kafka:29092 → acesso pelos outros containers
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
