// <auto-generated />
using System;
using BankMore.Tariffing.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMore.Tariffing.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250629161748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BankMore.Tariffing.Domain.Entities.Tariffing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateTransaction")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_tarifacao");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_tarifacao");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_transferencia");

                    b.HasKey("Id");

                    b.ToTable("tarifacao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
