// <auto-generated />
using System;
using BankMore.Transfer.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMore.Transfer.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250629021052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BankMore.Transfer.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CurrentAccountDestinationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_conta_corrente_destino");

                    b.Property<Guid>("CurrentAccountOriginId")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_conta_corrente_origem");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_transferencia");

                    b.Property<decimal>("TransferValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_transferencia");

                    b.HasKey("Id");

                    b.ToTable("transferencia", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
